Repository ultralytics/handbook, pull requests merged in 2024-10, with the labels that each got.

#1 Initial Handbook structure
  .github/workflows/links.yml
  README.md
  docs/company-guidelines/index.md
  docs/contributions/community-engagement.md
  docs/contributions/how-to-contribute.md
  docs/faq/index.md
  docs/goals/company-goals.md
  docs/goals/okrs.md
  docs/index.md
  docs/introduction.md
  docs/legal/licenses.md
  docs/legal/privacy-policy.md
  docs/mission-vision-values/index.md
  docs/mkdocs_github_authors.yaml
  docs/team-roles/index.md
  docs/team-roles/specific-roles.md
  docs/tools/developer-tools.md
  docs/tools/learning-resources.md
  docs/workflows/ci-testing.md
  docs/workflows/development.md
  docs/workflows/documentation.md
  docs/workflows/product-development.md
  mkdocs.yml
  template/README.md
  template/__init__.py
  template/module1.py
  tests/README.md
  tests/test_module1.py
Labels: dependencies, documentation, enhancement

#2 Update Handbook Structure
  .github/workflows/publish-handbook.yml
  .github/workflows/tag.yml
  docs/mkdocs_github_authors.yaml
  docs/overrides/assets/favicon.ico
  docs/overrides/javascript/extra.js
  docs/overrides/main.html
  docs/overrides/partials/comments.html
  docs/overrides/partials/source-file.html
  docs/overrides/stylesheets/style.css
  mkdocs.yml
Labels: documentation, enhancement

#6 Update links.yml
  .github/workflows/links.yml
Labels: enhancement

#7 Update tag.yml
  .github/workflows/tag.yml
Labels: dependencies

#8 Create CNAME
  docs/CNAME
Labels: documentation, enhancement

#9 Update README.md
  README.md
Labels: documentation, enhancement

#10 Ultralytics Code Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
  .github/workflows/tag.yml
  README.md
Labels: enhancement

#11 Update publish-handbook.yml
  .github/workflows/publish-handbook.yml
Labels: dependencies, enhancement

#14 Update publish-handbook.yml
  .github/workflows/publish-handbook.yml
Labels: enhancement

#15 Update tag.yml
  .github/workflows/tag.yml
Labels: dependencies, enhancement

#16 Values update
  docs/mission-vision-values/index.md
Labels: documentation, enhancement

#17 Delete docs/overrides/partials/source-file.html
  docs/overrides/javascript/extra.js
  docs/overrides/partials/source-file.html
Labels: documentation

#18 Update extra.js for auto theme
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement
