Repository ultralytics/handbook, pull requests merged in 2024-11, with the labels that each got.

#21 Use new Ultralytics Retry action
  .github/workflows/links.yml
  README.md
Labels: documentation, devops

#19 Adds dependencies and TOML updates
  pyproject.toml
Labels: dependencies, documentation, enhancement

#22 Reformat
  .github/workflows/publish-handbook.yml
  .github/workflows/tag.yml
  docs/overrides/javascript/extra.js
  docs/overrides/partials/comments.html
Labels: documentation, enhancement, devops

#23 Update Search Bar
  docs/overrides/javascript/extra.js
  docs/overrides/stylesheets/style.css
  mkdocs.yml
Labels: documentation

#25 Ultralytics Refactor https://ultralytics.com/actions
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#27 Apply these colors based on light/dark mode
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#28 Update extra.js
  docs/overrides/javascript/extra.js
Labels: enhancement

#29 Update favicon
  docs/overrides/assets/favicon.ico
  mkdocs.yml
Labels: documentation, enhancement
