Repository ultralytics/handbook, pull requests merged in 2025-04, with the labels that each got.

#53 Add Development team member Kiryl Oblikau
  docs/contributions/how-to-contribute.md
Labels: documentation

#54 Update links.yml
  .github/workflows/links.yml
Labels: documentation, devops

#55 Update links.yml
  .github/workflows/links.yml
Labels: documentation, devops

#56 Update extra.js with `0.3.20/dist/embed.min.js`
  docs/overrides/javascript/extra.js
Labels: dependencies, documentation, enhancement

#57 Update mkdocs_github_authors.yaml
  docs/mkdocs_github_authors.yaml
Labels: documentation

#58 Add .idea to .gitignore
  .gitignore
Labels: enhancement

#60 Update extra.js
  docs/community/community-engagement.md
  docs/community/how-to-contribute.md
  docs/community/index.md
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#61 Dark mode
  docs/mkdocs_github_authors.yaml
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#63 Update how-to-contribute.md
  docs/contributions/how-to-contribute.md
Labels: documentation

#64 Update mkdocs_github_authors.yaml
  docs/mkdocs_github_authors.yaml
Labels: documentation
