Repository ultralytics/handbook, pull requests merged in 2025-01, with the labels that each got.

#33 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#34 Update links.yml
  .github/workflows/links.yml
Labels: fixed, devops

#35 Add GitHub usernames
  docs/contributions/how-to-contribute.md
Labels: documentation, enhancement

#36 Update mkdocs.yml to 2025
  mkdocs.yml
Labels: documentation

#37 Standardize license headers in Python files
  docs/contributions/how-to-contribute.md
Labels: documentation

#38 Standardize license headers in TOML/YAML files
  .github/workflows/format.yml
  .github/workflows/links.yml
  .github/workflows/publish-handbook.yml
  .github/workflows/tag.yml
  docs/mkdocs_github_authors.yaml
  mkdocs.yml
  pyproject.toml
Labels: documentation, devops

#39 Fix link in how-to-contribute.md
  docs/contributions/how-to-contribute.md
Labels: documentation

#40 Add Jordan and Jake
  docs/contributions/how-to-contribute.md
Labels: documentation

#41 Update how-to-contribute.md
  docs/contributions/how-to-contribute.md
Labels: documentation

#42 mkdocs-ultralytics-plugin>=0.1.16
  pyproject.toml
Labels: dependencies, documentation

#43 Update mkdocs_github_authors.yaml
  docs/mkdocs_github_authors.yaml
Labels: documentation
