Repository ultralytics/handbook, pull requests merged in 2025-05, with the labels that each got.

#65 Kasim table update
  docs/contributions/how-to-contribute.md
Labels: documentation

#67 developers list update
  docs/contributions/how-to-contribute.md
Labels: documentation

#68 Update extra.js for trailing slash
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#69 Update extra.js
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#70 Update extra.js
  docs/overrides/javascript/extra.js
  docs/overrides/main.html
Labels: documentation, enhancement

#71 Update extra.js
  docs/overrides/javascript/extra.js
Labels: documentation, enhancement

#73 Update how-to-contribute.md
  docs/contributions/how-to-contribute.md
Labels: documentation

#74 Update development team profiles
  docs/contributions/how-to-contribute.md
Labels: documentation

#75 Add Permissions to Ultralytics Actions `format.yml`
  .github/workflows/format.yml
Labels: documentation, enhancement, devops
