Repository ultralytics/handbook, pull requests merged in 2025-08, with the labels that each got.

#93 docs: 📝 added myself as contributor (onuralpszr)
  docs/contributions/how-to-contribute.md
Labels: documentation

#95 Add Louis to the Development Team
  docs/contributions/how-to-contribute.md
Labels: documentation

#96 Update mkdocs_github_authors.yaml
  docs/mkdocs_github_authors.yaml
Labels: documentation

#97 Require `mkdocs-ultralytics-plugin>=0.1.26`
  pyproject.toml
  requirements.txt
Labels: dependencies, documentation

#98 Fix mkdocs.yml warnings
  mkdocs.yml
  pyproject.toml
  requirements.txt
  vercel.json
Labels: documentation

#99 Remove unneeded "cleanUrls": true` from vercel.json
  pyproject.toml
  requirements.txt
  vercel.json
Labels: documentation, devops

#100 Add new cities to Travel Per Diem rates
  docs/finance/travel.md
Labels: documentation, enhancement

#101 Fix links.yml to local repo scan
  .github/workflows/links.yml
Labels: dependencies, documentation, devops

#108 Fix Kiryl GitHub handle
  docs/contributions/how-to-contribute.md
Labels: documentation

#107 Add Abi Anderson to GitHub profiles
  docs/contributions/how-to-contribute.md
Labels: documentation

#109 Docs: YOLO Vision 2025 Banner
  docs/overrides/main.html
  docs/overrides/stylesheets/style.css
Labels: documentation

#110 New Relocation policy
  docs/finance/index.md
  docs/finance/relocation.md
  mkdocs.yml
Labels: documentation

#111 chore: remove click version lock as 8.2.2 was yanked
  pyproject.toml
Labels: dependencies

#112 Add Jin Xu to the Development Team
  docs/contributions/how-to-contribute.md
Labels: documentation

#105 Update Section 3: Add Notion forms process and security team contact.md
  docs/tools/software.md
Labels: documentation, enhancement

#116 Remove `click==8.2.1` from requirements.txt
  requirements.txt
Labels: dependencies, documentation

#118 Update pyproject.toml for `mkdocs-ultralytics-plugin>=0.1.29`
  pyproject.toml
Labels: dependencies, documentation

#121 Update mkdocs_github_authors.yaml
  docs/mkdocs_github_authors.yaml
Labels: documentation

#125 Fix code-of-business-conduct-and-ethics.md emoji in link
  docs/legal/code-of-business-conduct-and-ethics.md
Labels: documentation

#130 Update vercel.json
  vercel.json
Labels: enhancement, devops
