Repository ultralytics/handbook, pull requests merged in 2025-07, with the labels that each got.

#79 Update how-to-contribute.md
  docs/contributions/how-to-contribute.md
Labels: documentation

#82 Update pyproject.toml `mkdocs-ultralytics-plugin>=0.1.20`
  pyproject.toml
Labels: dependencies, documentation

#84 Update mkdocs_github_authors.yaml authors
  docs/mkdocs_github_authors.yaml
Labels: documentation

#86 Ultralytics Hardware Policy
  docs/finance/index.md
  docs/index.md
  docs/tools/developer-tools.md
  docs/tools/hardware.md
  docs/tools/index.md
  docs/tools/learning-resources.md
  docs/tools/software.md
  mkdocs.yml
Labels: documentation, enhancement

#87 New Email Signatures Automation
  docs/tools/email-signatures.md
  docs/tools/index.md
  mkdocs.yml
Labels: documentation, enhancement

#88 Update email-signatures.md
  docs/tools/email-signatures.md
Labels: documentation

#90 Update development team profiles
  docs/contributions/how-to-contribute.md
Labels: documentation

#91 Use `uv` in publish-handbook.yml
  .github/workflows/publish-handbook.yml
Labels: dependencies, documentation, devops
